highlighter: pygments
paginate: 10
markdown: kramdown
host: 0.0.0.0

kramdown:
  input: GFM
  hard_wrap: false

home_url: "https://Iyeonghun.github.io"
representing_image: "/images/og-logo.png"

sass:
    sass_dir: css

gems: [jekyll-paginate]
future: true